version: '3'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile.go
      args:
        - GO_VERSION=1.19
    env_file:
      - .env
    ports:
      - "$SERVER_PORT:$SERVER_PORT"

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        - PYTHON_VERSION=3.11
    env_file:
      - .env
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
    volumes:
      - cache_volume:/app/hacconsumer/cache
      - config_volume:/app/hacconsumer/config

volumes:
  cache_volume:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_CACHE_VOLUME_PATH}
      o: bind
  config_volume:
    driver: local
    driver_opts:
      type: none
      device: ${LOCAL_CONFIG_VOLUME_PATH}
      o: bind
