version: '3'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile.go
      args:
        - GO_VERSION=1.19
    env_file:
      - .env
    ports:
      - "$SERVER_PORT:$SERVER_PORT"

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
      args:
        - PYTHON_VERSION=3.11
    env_file:
      - .env
    ports:
      - "$FRONTEND_PORT:$FRONTEND_PORT"
    volumes:
      - ${LOCAL_CACHE_VOLUME_PATH}:/app/hacconsumer/cache
      - ${LOCAL_CONFIG_VOLUME_PATH}:/app/hacconsumer/config
